import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#333535",
        "on-secondary-container": "#bab8b7",
        "primary-fixed-dim": "#e9c176",
        "on-tertiary-container": "#3c3b3b",
        "on-surface-variant": "#d1c5b4",
        "surface-dim": "#121414",
        "surface-variant": "#333535",
        "tertiary-container": "#a7a5a4",
        "tertiary": "#c9c6c5",
        "on-tertiary-fixed-variant": "#474646",
        "primary-fixed": "#ffdea5",
        "surface": "#121414",
        "surface-container": "#1e2020",
        "on-primary": "#412d00",
        "surface-container-lowest": "#0d0e0f",
        "on-primary-container": "#4e3700",
        "error-container": "#93000a",
        "background": "#121414",
        "on-surface": "#e2e2e2",
        "outline-variant": "#4e4639",
        "secondary-container": "#4a4949",
        "on-secondary-fixed": "#1c1b1b",
        "inverse-primary": "#775a19",
        "on-background": "#e2e2e2",
        "secondary": "#c8c6c5",
        "inverse-on-surface": "#2f3131",
        "surface-bright": "#38393a",
        "on-tertiary": "#313030",
        "tertiary-fixed": "#e5e2e1",
        "on-secondary": "#313030",
        "error": "#ffb4ab",
        "primary-container": "#c5a059",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary-fixed": "#261900",
        "secondary-fixed": "#e5e2e1",
        "surface-tint": "#e9c176",
        "on-error": "#690005",
        "primary": "#e9c176",
        "inverse-surface": "#e2e2e2",
        "tertiary-fixed-dim": "#c9c6c5",
        "on-tertiary-fixed": "#1c1b1b",
        "outline": "#9a8f80",
        "surface-container-low": "#1a1c1c",
        "surface-container-high": "#282a2b",
        "on-secondary-fixed-variant": "#474646",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#5d4201",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-gap": "80px",
        "margin-mobile": "20px",
        "unit": "4px",
        "container-max": "1440px",
        "margin-desktop": "64px",
        "gutter": "24px",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "data-mono": ["IBM Plex Sans", "monospace"],
        "display-lg": ["Playfair Display", "serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.1em", fontWeight: "600" }],
        "data-mono": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
};

export default config;
